#!/usr/bin/env python3
"""Deploy a product demo to a cloud hosting platform."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path


PLATFORMS = ("vercel", "surge", "netlify", "cloudflare")

DEPLOYABLE_STACKS = ("web", "h5")

DEPLOY_DIR_MAP = {
    "web": "demo/web",
    "h5": "demo/h5",
}

PLATFORM_CLI_MAP = {
    "vercel": "vercel",
    "surge": "surge",
    "netlify": "netlify",
    "cloudflare": "wrangler",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Deploy a product demo to a cloud platform")
    parser.add_argument("--output-root", required=True, help="Delivery root generated by init_demo_delivery.py")
    parser.add_argument("--platform", choices=PLATFORMS, default="vercel", help="Deployment platform (default: vercel)")
    parser.add_argument("--project-name", default="", help="Project name / subdomain on the platform")
    parser.add_argument("--prod", action="store_true", help="Deploy to production (vs preview/draft)")
    parser.add_argument("--json", action="store_true", help="Print json summary")
    return parser.parse_args()


def check_npx() -> bool:
    return shutil.which("npx") is not None


def check_cli(platform: str) -> dict:
    """Check if the platform CLI is available via npx or globally."""
    cli_name = PLATFORM_CLI_MAP[platform]
    globally = shutil.which(cli_name) is not None
    return {"cli": cli_name, "global_install": globally, "npx_available": check_npx()}


def resolve_deploy_dir(output_root: Path, config: dict) -> Path | None:
    stack = config.get("stack", "")
    relative = DEPLOY_DIR_MAP.get(stack)
    if relative is None:
        return None
    deploy_dir = output_root / relative
    return deploy_dir if deploy_dir.is_dir() else None


def deploy_vercel(deploy_dir: Path, project_name: str, prod: bool) -> dict:
    cmd = ["npx", "vercel", "--yes"]
    if prod:
        cmd.append("--prod")
    if project_name:
        cmd.extend(["--name", project_name])
    result = subprocess.run(cmd, cwd=str(deploy_dir), capture_output=True, text=True, check=False)
    url = ""
    for line in result.stdout.strip().splitlines():
        stripped = line.strip()
        if stripped.startswith("http"):
            url = stripped
    return {
        "platform": "vercel",
        "url": url,
        "exit_code": result.returncode,
        "stdout": result.stdout.strip(),
        "stderr": result.stderr.strip(),
    }


def deploy_surge(deploy_dir: Path, project_name: str, _prod: bool) -> dict:
    domain = f"{project_name}.surge.sh" if project_name else ""
    cmd = ["npx", "surge", str(deploy_dir)]
    if domain:
        cmd.append(domain)
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    url = ""
    for line in result.stdout.strip().splitlines():
        stripped = line.strip()
        if "surge.sh" in stripped or stripped.startswith("http"):
            url = stripped if stripped.startswith("http") else f"https://{stripped}"
    return {
        "platform": "surge",
        "url": url,
        "exit_code": result.returncode,
        "stdout": result.stdout.strip(),
        "stderr": result.stderr.strip(),
    }


def deploy_netlify(deploy_dir: Path, project_name: str, prod: bool) -> dict:
    cmd = ["npx", "netlify-cli", "deploy", f"--dir={deploy_dir}"]
    if prod:
        cmd.append("--prod")
    if project_name:
        cmd.extend(["--site", project_name])
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    url = ""
    for line in result.stdout.strip().splitlines():
        if "http" in line:
            parts = line.split()
            for part in parts:
                if part.startswith("http"):
                    url = part
    return {
        "platform": "netlify",
        "url": url,
        "exit_code": result.returncode,
        "stdout": result.stdout.strip(),
        "stderr": result.stderr.strip(),
    }


def deploy_cloudflare(deploy_dir: Path, project_name: str, _prod: bool) -> dict:
    cmd = ["npx", "wrangler", "pages", "deploy", str(deploy_dir)]
    if project_name:
        cmd.extend(["--project-name", project_name])
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    url = ""
    for line in result.stdout.strip().splitlines():
        stripped = line.strip()
        if "pages.dev" in stripped or stripped.startswith("http"):
            if stripped.startswith("http"):
                url = stripped
            elif "http" in stripped:
                for part in stripped.split():
                    if part.startswith("http"):
                        url = part
    return {
        "platform": "cloudflare",
        "url": url,
        "exit_code": result.returncode,
        "stdout": result.stdout.strip(),
        "stderr": result.stderr.strip(),
    }


DEPLOYERS = {
    "vercel": deploy_vercel,
    "surge": deploy_surge,
    "netlify": deploy_netlify,
    "cloudflare": deploy_cloudflare,
}


def main() -> int:
    args = parse_args()
    output_root = Path(args.output_root).resolve()
    config_path = output_root / "demo-config.json"

    summary: dict[str, object] = {
        "output_root": str(output_root),
        "platform": args.platform,
        "status": "error",
        "url": "",
        "deployed_at": "",
    }

    if not config_path.exists():
        summary["error"] = f"demo-config.json not found at {config_path}"
        _output(summary, args.json)
        return 1

    config = json.loads(config_path.read_text(encoding="utf-8"))
    stack = config.get("stack", "")
    summary["stack"] = stack

    if stack not in DEPLOYABLE_STACKS:
        summary["error"] = (
            f"Stack '{stack}' does not support web deployment. "
            "Only 'web' and 'h5' demos can be deployed online. "
            "For SwiftUI demos, consider recording a video or sharing via a code repository."
        )
        _output(summary, args.json)
        return 1

    deploy_dir = resolve_deploy_dir(output_root, config)
    if deploy_dir is None:
        summary["error"] = f"Deploy directory not found for stack '{stack}'"
        _output(summary, args.json)
        return 1

    summary["deploy_dir"] = str(deploy_dir)

    cli_check = check_cli(args.platform)
    if not cli_check["global_install"] and not cli_check["npx_available"]:
        summary["error"] = (
            f"Neither '{cli_check['cli']}' nor 'npx' found. "
            f"Install Node.js and run: npm install -g {cli_check['cli']}"
        )
        _output(summary, args.json)
        return 1

    project_name = args.project_name or config.get("slug", "")
    deployer = DEPLOYERS[args.platform]
    result = deployer(deploy_dir, project_name, args.prod)

    summary["url"] = result["url"]
    summary["exit_code"] = result["exit_code"]
    summary["deployed_at"] = datetime.now().isoformat(timespec="seconds")

    if result["exit_code"] == 0 and result["url"]:
        summary["status"] = "success"
    elif result["exit_code"] == 0:
        summary["status"] = "deployed_but_url_not_captured"
        summary["hint"] = "Deployment may have succeeded. Check the platform dashboard for the URL."
    else:
        summary["status"] = "failed"
        summary["stderr"] = result["stderr"]

    _output(summary, args.json)
    return 0 if summary["status"] in ("success", "deployed_but_url_not_captured") else 1


def _output(summary: dict, as_json: bool) -> None:
    if as_json:
        print(json.dumps(summary, ensure_ascii=False, indent=2))
    else:
        status = summary.get("status", "error")
        if status == "success":
            print(f"Deployed to {summary['platform']}: {summary['url']}")
        elif "error" in summary:
            print(f"Error: {summary['error']}", file=sys.stderr)
        else:
            print(f"Deploy status: {status}")
            if summary.get("stderr"):
                print(summary["stderr"], file=sys.stderr)


if __name__ == "__main__":
    raise SystemExit(main())
