#!/usr/bin/env python3
"""Validate product demo deliverables."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


BRIEF_HEADINGS = (
    "## 1. 演示目标",
    "## 2. 目标受众与场景",
    "## 3. 平台与设备",
    "## 4. 必须展示的路径",
)

DESIGN_SYSTEM_HEADINGS = (
    "## 1. 产品气质",
    "## 2. 页面结构",
    "## 3. 色板与字体",
    "## 4. 核心组件",
    "## 6. Anti-patterns",
)

CHECKLIST_HEADINGS = (
    "## 1. 可演示性",
    "## 2. 视觉与信息层次",
    "## 3. Accessibility",
    "## 4. Metadata 与分享准备",
    "## 5. Motion Performance",
)

WALKTHROUGH_HEADINGS = (
    "## 1. 演示顺序",
    "## 2. 每一步要强调什么",
    "## 3. 推荐话术",
)

HANDOFF_HEADINGS = (
    "## 1. 交付概览",
    "## 2. 运行方式",
    "## 3. 关键文件",
    "## 4. 已知限制",
)

DEMO_README_HEADINGS = (
    "## 1. 入口说明",
    "## 2. 快速预览",
    "## 3. 文件结构",
    "## 4. 当前限制",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate demo brief, design system, demo files, and handoff docs")
    parser.add_argument("--output-root", required=True, help="Delivery root generated by init_demo_delivery.py")
    return parser.parse_args()


def validate_markdown(path: Path, headings: tuple[str, ...]) -> dict:
    result = {"path": str(path), "exists": path.exists(), "missing_headings": []}
    if not path.exists():
        return result
    content = path.read_text(encoding="utf-8")
    result["missing_headings"] = [heading for heading in headings if heading not in content]
    return result


def validate_stack_assets(output_root: Path, stack: str) -> dict:
    result = {"stack": stack, "missing_files": [], "content_issues": []}
    if stack == "web":
        html_path = output_root / "demo" / "web" / "index.html"
        if not html_path.exists():
            result["missing_files"].append(str(html_path))
        else:
            content = html_path.read_text(encoding="utf-8")
            if "<title>" not in content:
                result["content_issues"].append("web index.html 缺少 <title>")
            if "viewport" not in content:
                result["content_issues"].append("web index.html 缺少 viewport")
    elif stack == "h5":
        html_path = output_root / "demo" / "h5" / "index.html"
        if not html_path.exists():
            result["missing_files"].append(str(html_path))
        else:
            content = html_path.read_text(encoding="utf-8")
            if "<title>" not in content:
                result["content_issues"].append("h5 index.html 缺少 <title>")
            if "viewport-fit=cover" not in content:
                result["content_issues"].append("h5 index.html 缺少 viewport-fit=cover")
    elif stack == "swiftui":
        files = {
            "DemoApp.swift": "@main",
            "ContentView.swift": "struct ContentView: View",
            "DesignTokens.swift": "enum DemoTokens",
        }
        for filename, snippet in files.items():
            candidate = output_root / "demo" / "swiftui" / filename
            if not candidate.exists():
                result["missing_files"].append(str(candidate))
                continue
            content = candidate.read_text(encoding="utf-8")
            if snippet not in content:
                result["content_issues"].append(f"{filename} 缺少关键片段: {snippet}")
    else:
        result["content_issues"].append(f"不支持的 stack: {stack}")
    return result


def main() -> int:
    args = parse_args()
    output_root = Path(args.output_root).resolve()
    config_path = output_root / "demo-config.json"
    summary: dict[str, object] = {
        "output_root": str(output_root),
        "config_exists": config_path.exists(),
        "documents": {},
        "missing_files": [],
        "stack_validation": {},
    }

    if not config_path.exists():
        summary["missing_files"] = [str(config_path)]
        print(json.dumps(summary, ensure_ascii=False, indent=2))
        return 1

    config = json.loads(config_path.read_text(encoding="utf-8"))
    stack = str(config.get("stack") or "").strip()

    documents = {
        "brief": (output_root / "brief" / "demo-brief.md", BRIEF_HEADINGS),
        "design_system": (output_root / "design-system" / "MASTER.md", DESIGN_SYSTEM_HEADINGS),
        "checklist": (output_root / "review" / "preflight-checklist.md", CHECKLIST_HEADINGS),
        "walkthrough": (output_root / "review" / "demo-walkthrough.md", WALKTHROUGH_HEADINGS),
        "handoff": (output_root / "handoff" / "developer-handoff.md", HANDOFF_HEADINGS),
        "demo_readme": (output_root / "demo" / "README.md", DEMO_README_HEADINGS),
    }

    missing_files: list[str] = []
    has_document_issue = False

    for key, (path, headings) in documents.items():
        result = validate_markdown(path, headings)
        summary["documents"][key] = result
        if not result["exists"]:
            missing_files.append(str(path))
            has_document_issue = True
        elif result["missing_headings"]:
            has_document_issue = True

    page_override = output_root / "design-system" / "pages" / "home.md"
    if not page_override.exists():
        missing_files.append(str(page_override))

    stack_validation = validate_stack_assets(output_root, stack)
    summary["stack_validation"] = stack_validation
    summary["missing_files"] = missing_files + stack_validation["missing_files"]

    print(json.dumps(summary, ensure_ascii=False, indent=2))

    if has_document_issue or summary["missing_files"] or stack_validation["content_issues"]:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
